// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "24df568e-74d7-473d-8948-8c72d55e161a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1594562199);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1594562391);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594562271);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3757);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1594562169);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2531dfdd-cea9-48bb-9619-fcd69e28cf00}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1594562228372");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1594564056372");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1594562175415");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1594565775415");
user_pref("browser.search.region", "JP");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200707170725");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20200707170725");
user_pref("browser.startup.homepage_override.mstone", "68.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1594562649);
user_pref("browser.tabs.remote.autostart", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1594562173619");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.redhat.bookmarksProcessed", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200707170725");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.privatebrowsing.notification", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a10b21ec-016e-4c2b-a6d8-5f616c6431d2\",\"fxmonitor@mozilla.org\":\"fe126be5-a2a7-494c-ad39-18131b87386e\",\"screenshots@mozilla.org\":\"ef06f8cf-2be5-4927-9b4a-09589aec64c1\",\"webcompat-reporter@mozilla.org\":\"7d8f5565-7bb0-4827-a4fd-6ed20d3b3d0f\",\"webcompat@mozilla.org\":\"57998990-8b6b-4ab3-92bb-953f2fcbec20\",\"default-theme@mozilla.org\":\"3bbda78a-0d9b-480c-ab77-871474f7e16c\",\"google@search.mozilla.org\":\"52039c1a-bb93-455b-bbeb-3abe72c594df\",\"amazondotcom@search.mozilla.org\":\"b20952e9-6221-470c-8f77-b049deeb7db9\",\"bing@search.mozilla.org\":\"64058661-f169-4024-ac9f-daf9499337da\",\"ddg@search.mozilla.org\":\"ad6ff38c-f0e2-498c-8500-bba5b71d1402\",\"ebay@search.mozilla.org\":\"8fe00fac-209a-4075-a6f0-59022d861818\",\"twitter@search.mozilla.org\":\"68cb5e68-7e86-4bb9-99f4-171168412471\",\"wikipedia@search.mozilla.org\":\"ed3b173c-3497-45b9-93b1-87a1ddf136e6\",\"yahoo-jp@search.mozilla.org\":\"fc952af2-6c0e-48df-b0ac-8763d0eb48ff\",\"amazon@search.mozilla.org\":\"21f6b252-decc-4907-a34a-c90a7ffed706\",\"rakuten@search.mozilla.org\":\"ca738a61-6013-4216-9560-f3fcb1cc269e\",\"yahoo-jp-auctions@search.mozilla.org\":\"0c8860fb-988e-46fa-b58e-8dcb8bc8c369\",\"oshiete-goo@search.mozilla.org\":\"21cdd44b-b889-43dd-a507-34a30ebee2e5\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("intl.locale.requested", "ja");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "b932f484-b8f5-4ff6-aac5-a51e12f757bf");
user_pref("security.sandbox.plugin.tempDirSuffix", "7b479213-cae6-402a-9766-2b9dd52a5543");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1594562646);
user_pref("toolkit.telemetry.cachedClientID", "8efdd9d7-1e0c-4c7d-8dfb-792a2de717c6");
user_pref("toolkit.telemetry.previousBuildID", "20200707170725");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
