---
apiVersion: v1
kind: Service
metadata:
  name: centos-xfce-ja
spec:
  selector:
    app: centos-xfce-ja
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080


