# Reverse Proxy Setting
# VNC      -> http://yourhost:8080/desktop -> 127.0.0.1:6901
# Terminal -> http://yourhost:8080/term    -> 127.0.0.1:57575

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8080"

[file]

[backends]
  [backends.linux-vnc]
    [backends.linux-vnc.servers.vnc1]
    url = "http://127.0.0.1:6901/"
    weight = 1
  [backends.linux-term]
    [backends.linux-term.servers.term1]
    url = "http://127.0.0.1:57575/"
    weight = 1

[frontends]
  [frontends.linux-vnc]
  backend = "linux-vnc"
  passHostHeader = true
    [frontends.linux-vnc.routes.desktop]
    rule = "PathPrefixStrip:/desktop"

  [frontends.linux-app]
  backend = "linux-vnc"
  passHostHeader = true
    [frontends.linux-app.routes.app]
    rule = "PathPrefix:/app/"

  [frontends.linux-core]
  backend = "linux-vnc"
  passHostHeader = true
    [frontends.linux-core.routes.core]
    rule = "PathPrefix:/core/"

  [frontends.linux-vendor]
  backend = "linux-vnc"
  passHostHeader = true
    [frontends.linux-vendor.routes.vendor]
    rule = "PathPrefix:/vendor/"

  [frontends.linux-websockify]
  backend = "linux-vnc"
  passHostHeader = true
    [frontends.linux-websockify.routes.websockify]
    rule = "PathPrefix:/websockify"

  [frontends.linux-term]
  backend = "linux-term"
  passHostHeader = true
    [frontends.linux-term.routes.vnc]
    rule = "PathPrefix:/term"

